---
- name: create ansible tomcat directory
  file:
    path: /usr/share/tomcat/webapps/ROOT
    state: directory

- name: copy static index.html
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644
- name: restart tomcat
  service:
    name: tomcat
    state: restarted
