[all:vars]
GUID=c16d

[internal:vars]


all:
  hosts:
    bastions:
      hosts:
        bastion:
          ansible_host: bastion.{{ GUID }}.example.opentlc.com
    frontends:
      hosts:
        frontend1:
          ansible_host: frontend1.{{ GUID }}.internal
    apps:
      hosts:
        app1:
          ansible_host: app1.{{ GUID }}.internal
        app2:  
          ansible_host: app2.{{ GUID }}.internal
    appdbs:
      hosts:
        appdbs1:
          ansible_host: appdbs1.{{ GUID }}.internal




[internal:children]
frontends
apps
appdbs


all:
  hosts:
    mail.example.com
  children:
    webservers:
      hosts:
        foo.example.com:
        bar.example.com:
    dbservers:
      hosts:
        one.example.com:
        two.example.com:
        three.example.com:
